### PR TITLE
Fix incorrect values for numbers over 999

### PR DESCRIPTION
**Pull request by MattyBalaam**
Run regex to strip out commas from numbers before running parseInt()

https://github.com/tractorcow/silverstripe-sliderfield/issues/9

### CODE REVIEW

**Comment by MattyBalaam** [comment]
I’m just thinking out loud, I’ve not used this module for a while. Does the sliderfield allow decimals?

**Comment by ggrune** [comment]
The regex solution smells like a dirty hack (@MattyBalaam sorry it's not personal). 
A better solution should avoid the formatted representation of the numeric value. 
`<input type="text" value="1900" data-min="400" data-max="1900">`
instead of 
`<input type="text" value="1.900" data-min="400" data-max="1900">`
But I'm not familiar with jquery, javascript and the slider. Maybe some one else find a better solution.

**Comment by MattyBalaam** [comment]
I agree :) At the time it seemed like a good idea.

With Silverstripe 4 moving to React, using a component is perhaps a better long-term option

**Comment by tractorcow** [comment]
We could use input type=number instead, and I believe that fixes it to numeric only.

**Comment by ggrune** [comment]
I have found a solution to initialize the value of the input field the unformatted value #11

**Comment by tractorcow** [comment]
Replaced with https://github.com/tractorcow/silverstripe-sliderfield/pull/11

**Pull request closed without merging**
